travis:
  secure:
    BINSTAR_TOKEN: J0nNU8vcpWO3n+ZCH1XmtqwB1BxUq8/kpDafy2UXc22DTvMbT9jp6GML3XfQSSOd58s/vS9EQW219mL695jDPEKrdu1MoLoywkuJ6BeA9LEGcYW7S6jtJ0gnTNU3EX5Ifr569V85AYCBWUpifYd4gx1pAUPFsNxR/K4NFDGAo95y2QGLXLaLOlqZ78yL4d0d7RXsEe5OBHJTy2hO6jUtky584uRFWgYTTktnNyteZYYlGyBAcM/5UaluIo195gDMv5v7ULKSyyZNa9nKJjZGZtIgwD+JX6mQSV3JF5DsWVSBOm7aOIcBGx/OARfXqv0+Gms3LZLomISEjqJcLl6S3bTDooQ2fZLqPIPkNn233NlcXqp84ML0ARtnr/I9G/mzTI26rDRyZhKyqkX3ILhACB003fhTms2VOFyXO1VB8dWCRR0+39kbpnIDUQ1FTsB5Cci3KgMDfMn81tPXfhpGYdgZRIAf8anfDv6qBGGNPXFcfU/XoQVVZDlTBuJV41Dt+vGAg+3pFJSqUlONjERqOS+LMYSapzM2LW+5Yj2pV3D0BVOXdpmnu11FOQqkzgnBOR9jabPWjvmf2t72LbpjvbSUtOeJ8T7Oa4ho2JGSaKfUCRTTjiZO+apXngjR1NE1vRzN8nj+lpyp6I8oFMG5CTBv/mumnmI57LF8LLp+wuk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
