travis:
  secure:
    BINSTAR_TOKEN: evmYCiFC/PZM5KJINBBE31YIAt4Nrsv8Y+2FX55IxQQHC3nPWUKLNr81Dcl6qFMGf6Np1dkbizH8/4moNQiozC71dIXyBirr9RzDcrgP/3VH5RyzVRxXizNHQY7QHtN1fNiDXv8wMRQ3BIKsnAmVthlk91dvGwy1VCp0Uv6gq+1eCEHOSen/rFmzSu+X44Ekdh6/PEEl/wFvlI8up3hvu6K1RZ7W/coPc2CIAwVMpevW2ycNQwNdUSrgYDAnK1s24QlAukpSOH31G52M/QA1+eae0b+ynLSogY8UNdW5Sdx0o2AJSOCR2ihjL94ll8ocUfiFCErhWymKMte2okqixTcJrMoawr+ooxT1KxOaMlZX9Ujxt5CpTPuWLM+ezyQPqvi6++zVv19EZGbGLfyWL1xuYyLE/P6CCnnucNumF8GcTCck5k5jFUMpDxo4zENpBQb+A/ODxYXAHwfXM8SyWYWOmpuPDKkUyLpLA/uzONp/8sMqdHSfpsZssLTr3CDfoQEMPAHfaROBX51ZQ+Diw/Jw+pZ0F5rcDMMTp80jAomTtC0le/oxoQnXJFp9ImTE4lup2byboRT5N7yPP2LgxXunKCoviEl7DZBAne451rUfGFCRtNAlcHSxSrvw2Cn0xLo87RTTs2PaFiYPRaKk+mw6TTcTHAB3rTGmWEg4gWI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
